// JavaScript Document
var quotes = [
	'He knows that Simba means lion in Swahili.',
	'He is the king of bees and friend of cats.',
	'He has come to peace with the fact he does not "get" jazz.',
	'His top three albums are; Placebo-S/T, BTMI!-Vacation and Rage against the Machine-Evil Empire.',
	'He collects Super Nintendo games.',
	'He keeps the ticket of every gig he has ever been to.',
	'His favourite piece of art is Flag by Jasper Johns.',
	'His top three movies are The Empire Strikes Back (1980), The Shining (1980) and The Thing (1982).',
	'He once beat the first level of the original Super Mario Bros with his eyes closed while a friend shouted instructions. Once.',
	'His favourite book is a tie between Bram Stokers Dracula and Joseph Hellers Catch-22.',
	'He makes the best Blueberry Pancakes this side of the Atlantic.',
	'He cannot ride a unicycle.',
	'He cannot ride a bicycle. Never learnt.',
	'He is just over 6"7.',
	'When he was fifteen, he used to play bass in a punk(ish) band. It was fun.',
	'He once completed The Ocarina of Time over thirty six hours in two sessions with two of his best friends.',
	'He owns a magic 8-Ball.',
	'He only dances like nobodies watching when nobodies watching.',
	'He realises how annoyingly quriky this list of pointless facts is. He just doesnt care.',
	'He thinks Game of Thrones went downhill in the fourth season, but thats just his opinion.',
	'He loved the character development of Rey and Finn in the Force Awakens, and feels they wasted it completely in the Last Jedi.',
	'He has a life size cutout of Darth Vader from a 1997 Walkers Crisps promotion in his living room.',
	'His favourite X-Men are Cannonball, Chamber, Beak and Husk (from the Age of Apocolypse storyline).',
	'He cant think of a fact to put here.',
	'He fell in love with drawing because of the N64 game "1080 Snowboarding", and would spend hours copying the character designs from the instruction manual.',
	'Despite being close friends with several avid players, he has only ever played DnD once.',
	'He saw Sonic Youth once, which was pretty cool.',
	'If he could see one band who are no longer active, it would be the Beastie Boys. Johnny Cash is a close second.',
	'He worked in a FedEx warehouse for two summers in sixth form and got all of his friends jobs there.',
	'His favourite classic cartoon is Will E Coyote and Roadrunner.',
	'His favourite flavour of milkshake is vanilla, although a good mint-choc-chip can win on occasion.',
	'He once attempted to ride a friends unicycle. It didnt go well.',
	'The furthest east he has travelled is Shanghai, furthest west is New York.',
	'He can dance if he wants to, he can leave his friends behind, cause his friends dont dance and if they dont dance, well, theyre still his friends even if they dont always share the same interests.',
	'He used to be really good at Halo 2. Like, really good.',
	'He cant pick a favourite animal. But hedgehogs are pretty relatable.',
	'He is trying to be funny.',
	'He probably drinks too much coffee.',
	'His favourite Disney movie (classic animation) is Hercules.',
	'He thought he could skateboard after playing Tony Hawks Pro Skater. He was wrong.',
	'He thinks Adidas are the coolest trainers, especially in bright red.',
	'Bean bags are his favourite form of chair.',
	'If he had to be an animal for a day, he would be the one that doesnt have to answer that question.', 
	'He once rode a toboggan from a checkpoint on the Great Wall of China.',
	'He honestly believed Neville Longbottom would turn out to be the chosen one.',
	'He never got a letter from Hogwarts, so he went with graphic design instead.',
	'He doesnt run, not because its hard, but because he looks stupid doing it.',
	'He once met Robbie Coltrane. It didnt go well.',
	'His favourite cities are New York, Barcelona, Istanbul and Shanghai.',
	'He is a world class face-puller.',
	'Hes pretty good at staring contests and thumb wars, but not unbeatable.',
	'Svalbard is at the top of his travelling bucket list.',
	'His favourite chocolate is classic M&Ms.',
	'He built this entire website from scratch.',
	'He has been up the Empire State Building twice.',
	'He would like to learn how to play the Cello one day.',
	'His favourite sandwich is a Salt Beef Reuben.',
	'His favourite board game is Risk.',
	'He isnt a bird, or a plane. He isnt Superman either.',
	'His favourite podcasts are Lore, Spirits and Hardcore Histories.',
	
	'He needs a new set of speakers for his stereo, and wont shut up about it.',
	'His favourite poem is "Ozymandias" because he doesnt know that much about poetry.',
	'His top character choices in Smash Brothers are Falcon and Little Mac. He doesnt win much.',
	'He once got stranded in London with nothing but his portfolio and a copy of an Aesop Rock album. Its a pretty funny story.',
	'His favourite Lord of the Rings movie is the Fellowship of the Ring.',
	'His favourite Marvel movie is Thor Ragnarok.',
	'His favourite Zelda game is Majoras Mask, although mostly for sentimental reasons as Breath of the Wild is the best.',
	'He hates mushrooms.',
	
	

]

function newQuote() {
	var randomNumber = Math.floor(Math.random() * (quotes.length));
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}